export const samplePlayers = [
  {
    id: "p1",
    name: "Aarav Mehta",
    age: 18,
    dominantSkill: "batting",
    battingHand: "right",
    bowlingStyle: "none",
    notes: "Aggressive opener with strong powerplay intent.",
  },
  {
    id: "p2",
    name: "Rohan Iyer",
    age: 19,
    dominantSkill: "all-rounder",
    battingHand: "left",
    bowlingStyle: "pace",
    notes: "Reliable middle-overs all-round option.",
  },
  {
    id: "p3",
    name: "Neil Kapoor",
    age: 18,
    dominantSkill: "bowling",
    battingHand: "right",
    bowlingStyle: "spin",
    notes: "Leg-spinner with wicket-taking variation.",
  },
  {
    id: "p4",
    name: "Vihaan Sethi",
    age: 17,
    dominantSkill: "wicketkeeper",
    battingHand: "right",
    bowlingStyle: "none",
    notes: "Sharp gloves and quick running between wickets.",
  },
  {
    id: "p5",
    name: "Kabir Shah",
    age: 19,
    dominantSkill: "batting",
    battingHand: "left",
    bowlingStyle: "none",
    notes: "Anchor profile; rotates strike efficiently.",
  },
  {
    id: "p6",
    name: "Aditya Rao",
    age: 18,
    dominantSkill: "bowling",
    battingHand: "right",
    bowlingStyle: "pace",
    notes: "Death overs specialist.",
  },
];

export const sampleMatches = [
  {
    id: "m1",
    date: "2026-03-10",
    teamA: "Blue Blazers",
    teamB: "Green Guards",
    winner: "Blue Blazers",
    venue: "Riverfront Ground",
    matchType: "T20",
    stats: [
      { playerId: "p1", runs: 54, ballsFaced: 32, fours: 6, sixes: 2, wickets: 0, oversBowled: 0, runsConceded: 0, catches: 1, runOuts: 0 },
      { playerId: "p2", runs: 32, ballsFaced: 24, fours: 2, sixes: 1, wickets: 2, oversBowled: 4, runsConceded: 27, catches: 0, runOuts: 1 },
      { playerId: "p3", runs: 11, ballsFaced: 9, fours: 1, sixes: 0, wickets: 3, oversBowled: 4, runsConceded: 23, catches: 1, runOuts: 0 },
      { playerId: "p4", runs: 21, ballsFaced: 17, fours: 2, sixes: 0, wickets: 0, oversBowled: 0, runsConceded: 0, catches: 2, runOuts: 0 },
      { playerId: "p5", runs: 38, ballsFaced: 31, fours: 4, sixes: 0, wickets: 0, oversBowled: 0, runsConceded: 0, catches: 0, runOuts: 0 },
      { playerId: "p6", runs: 9, ballsFaced: 7, fours: 0, sixes: 1, wickets: 2, oversBowled: 4, runsConceded: 25, catches: 1, runOuts: 0 },
    ],
  },
  {
    id: "m2",
    date: "2026-03-17",
    teamA: "Green Guards",
    teamB: "Red Rockets",
    winner: "Green Guards",
    venue: "Hilltop Turf",
    matchType: "T10",
    stats: [
      { playerId: "p1", runs: 24, ballsFaced: 14, fours: 2, sixes: 2, wickets: 0, oversBowled: 0, runsConceded: 0, catches: 0, runOuts: 0 },
      { playerId: "p2", runs: 28, ballsFaced: 20, fours: 1, sixes: 1, wickets: 1, oversBowled: 2, runsConceded: 14, catches: 1, runOuts: 0 },
      { playerId: "p3", runs: 7, ballsFaced: 6, fours: 1, sixes: 0, wickets: 2, oversBowled: 2, runsConceded: 11, catches: 0, runOuts: 0 },
      { playerId: "p4", runs: 16, ballsFaced: 12, fours: 1, sixes: 0, wickets: 0, oversBowled: 0, runsConceded: 0, catches: 1, runOuts: 1 },
      { playerId: "p5", runs: 42, ballsFaced: 23, fours: 5, sixes: 1, wickets: 0, oversBowled: 0, runsConceded: 0, catches: 0, runOuts: 0 },
      { playerId: "p6", runs: 5, ballsFaced: 4, fours: 1, sixes: 0, wickets: 1, oversBowled: 2, runsConceded: 16, catches: 0, runOuts: 0 },
    ],
  },
];
